### ISSUE TITLE
Refactor out redundancies in RegularFunctions and Ordering

### ISSUE THREAD

**Issue by rubensworks** [comunica/sparqlee#178]
Functions such as lessThan, greaterThan, ... contain many redundancies.
Is there a reason why we can not rewrite all of them in terms of the ordering logic in Ordering?

@jitsedesmet perhaps you have some insights into this?

**Comment by jitsedesmet** [comment]
Good question, I can't think of a reason why this wouldn't work, seems like Ordering only requires things in the SharedContext and this is available in the Regularfunctions. I think we should try it.

**Comment by jitsedesmet** [comment]
For [a Comunica issue](https://github.com/comunica/comunica/issues/1212#issuecomment-1562513421) I also wanted to rewrite some aggregators to use the Ordering syntax. In the same PR I will look into this issue?

**Comment by rubensworks** [comment]
Maybe we can start with just #1212, and leave this issue here for a later date (as I expect it will require a significant effort).
