### ISSUE TITLE
Test general concepts

### ISSUE THREAD

**Issue by wschella** [comunica/sparqlee#35]
There are a lot of general concepts (error handling, type promotion, EBV), that are implemented, but at the best loosely tested trough some unrelated tests.

Things we should definitely still test:

- [ ] Error handeling
- [ ] Subtype subsitution
- [ ] Type promotion
- [ ] Handling of nonlexicals
- [ ] Coercing to EBV
- [ ] Exists / aggregate hook

**Comment by jitsedesmet** [comment]
My report:

For error handling, we should have the error table. Even though we could write more tests, our test suite allows us to easily add them, and there are already a few locations where we use them. I suggest we ignore this for now.

For Subtype substitution, I will implement some more tests. 

Type promotion has some test introduced in https://github.com/comunica/sparqlee/pull/103/files#diff-4db5dd024582568f1ac1245e2af228c5611a35cca8d33e741db5ac081ddd2c28

Handling of non-Lexical forms has some minimal tests. (for example, in addition)

Will add some tests regarding Coercing to EBV.

Exists has a test https://github.com/jitsedesmet/comunica/blob/master/packages/expression-evaluator/test/integration/misc/Exists-test.ts
I don't think we have a test for the aggregate hook. The creation of a Comunica engine test might bé the best way to test them. (@rubensworks now that sparqlee is a package within Comunica this should suffice to close this issue?)

**Comment by rubensworks** [comment]
> I don't think we have a test for the aggregate hook. The creation of a Comunica engine test might bé the best way to test them. 

Sounds good!
