### ISSUE TITLE
Test both async and sync implementations

### ISSUE THREAD

**Issue by wschella** [comunica/sparqlee#36]
Currently the test script always uses the async implementation. This way however we have no clue whether the sync one works as well. And although it has the same logic largely, there are some differences, certainly for the special functions.

**Comment by jitsedesmet** [comment]
I will try to close this issue by creating `generalEvaluation`. This will evaluate both sync and async in case a syncConfig object is provided and Test only async in case an asyncConfig object is provided.

**Comment by wschella** [comment]
Great that you found them!

**Comment by jitsedesmet** [comment]
Report:
* The `in` / `notin` test: a return was forgotten.
* The bnode test: the test was statefull and interfered with the way `generalEvaluation` works.
