### ISSUE TITLE
Test all functions

### ISSUE THREAD

**Issue by wschella** [comunica/sparqlee#37]
The spec tests are very insufficient for testing all logic (certainly in regards to types) of all functions. For every function we should add a test ourselves.

**Comment by jitsedesmet** [comment]
I think this issue can be closed? Haven't checked manually, but I don't see how we could have got 100% coverage if we don't test all functions.

**Comment by wschella** [comment]
It originally meant better testing (for all functions). The fact that you have full coverage doesn't necessarily means you test all cases between interacting functions. And the spec tests don't cover much. That said, this issue is a bit too vague, but we should be aware there is room for more tests, especially w.r.t. typing logic.

**Comment by jitsedesmet** [comment]
I agree. Better tests could be beneficial. However, since we can not test **everything** and I don't see any benefit in transferring this issue to Comunica, I will close it.
