### ISSUE TITLE
Spec compliant number representation & precision

### ISSUE THREAD

**Issue by wschella** [comunica/sparqlee#45]
The [SPARQL-spec] uses multiple numeric datatypes from the [xsd-spec](https://www.w3.org/TR/xmlschema-2/).
These types have a fixed representation, minimal value, maximum value, precision, ...

Currently none of this is checked by us, and everything is the JS number datatype, which is a "a double-precision 64-bit binary format IEEE 754 value", i.e. a double in C, f64 in Rust. 

- [ ] Parse (and mostly validate) incoming values correctly
- [ ] Store internally at the correct precision through libraries such as decimal.js
- [ ] Handle correctly during operations such as addition (i.e. should we overflow, widen the type?)
- [ ] Handle correctly during Type Promotion (#12 )
- [ ] Export and print in the correct lexical form (although I think this is already the case)

Ideally the strictness is all quite configurable.

**Comment by jitsedesmet** [comment]
> Handle correctly during operations such as addition (i.e. should we overflow, widen the type?)

We already fixed and documented this I think? In code: https://github.com/comunica/sparqlee/blob/master/lib/functions/Helpers.ts#L214-L224

And more precisely in the url talked about there: https://www.w3.org/TR/xpath20/#mapping
We see a table that talks about the types.

**Comment by wschella** [comment]
I'm not sure about anything, it's been a while and there have been many changes.

I do think however that 3 might not be implemented correctly. If you add two limited width integers (e.g. shorts), and the result of their addition or multiplication exceeds the bounds of the datatype, what are we supposed to do? JS won't complain, and we will serialize a number too big, but still call it xsd:short. What does the spec mention about overflow? Either we have to widen the datatype, do modulo arithmetics?

Related, I don't think we validate that when we receive an xsd:short, whether it iactually fits into an xsd:short. Not saying we should error, but a warning would be good, or at least an optino to trigger a warning.

I would make separate new issues for this in the communica repo.

**Comment by jitsedesmet** [comment]
Oh yeah! I misunderstood. Thank you!

**Comment by jitsedesmet** [comment]
I will close this issue in favour of three issues created on the Comunica repo:
* https://github.com/comunica/comunica/issues/1265
* https://github.com/comunica/comunica/issues/1264
* https://github.com/comunica/comunica/issues/1266
